Rspec
mcihadkurel/Enumerable-methods pull request #8
Opened 2020-09-04 14:46 UTC by mcihadkurel

### Rspec testing for Enumerable Methods
**İn this project:**
1-) We added all test cases.
2-) We covered all edge cases, empty inputs. Block, procs, argument, and symbols.
3-) Fixed all rubocop errors.

2020-09-04 15:47 UTC, Dandush03 requested changes
# Status: :red_circle: Require Changes :red_circle: 
### You're almost done! :partying_face: 

- [ ] #multiply_els not been tested 
### Since we are learning TDD we need to be sure to test each scenario possible in our code.
# Happy Coding :computer: :nerd_face:

2020-09-04 18:44 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [ ] Some test are failing, lets fix that.
- [ ] Lets remove this in the main.rb .
````ruby
array = [5, 9, 10]
my_proc = proc { |num| num > 6 }
p [2, 54, 6, 7].my_map(my_proc) { |num| num < 10 }
p 5.times.my_inject(20, :*)
p 5.times.inject(20, :*)
p multiply_els(array)
````
- [ ] check the comment below

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-04 18:44 UTC, kobiyoyo commented on main.rb
>  end
You have a duplicate of this `multiply_els(array)` ,lets remove one

2020-09-04 20:09 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [ ] Some tests are still failing, let's fix that.

![1](https://user-images.githubusercontent.com/23278161/92281034-a7076f00-eef2-11ea-97b0-a5f6f36ba401.png)

- [ ] Lets remove this code that is in the main.rb .
````ruby
array = [5, 9, 10]
my_proc = proc { |num| num > 6 }
p [2, 54, 6, 7].my_map(my_proc) { |num| num < 10 }
p 5.times.my_inject(20, :*)
p 5.times.inject(20, :*)
p multiply_els(array)
````
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-05 00:39 UTC, kobiyoyo requested changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap: 
Just a few minor issues to fix
- [ ] lets rename the file from `enumerables_testing.rb` to `enumerables_testing_spec.rb`
- [ ] In the `enumerables_testing_spec.rb` change the main.rb file path to `require_relative '../main.rb'`
#### You can merge once done  !!!

2020-09-05 00:39 UTC, kobiyoyo approved these changes
Project Approved

2020-09-07 07:54 UTC, merged